### ISSUE TITLE
Duplicated footnote can't refer correctly

### ISSUE THREAD

**Issue by jackycute** [markdown-it/markdown-it-footnote#13]
Hi, really love this project.

@rlidwka 
I saw you made some commit on the logs.
But in this line https://github.com/markdown-it/markdown-it-footnote/blob/master/index.js#L38
That cause the reference href link to nowhere.
Because the footnote's id doesn't contain that colon and the duplicate number.

For example:
```
Footnote[2]. <-- href is "#fn2"
Duplicated footnote reference[2:1]. <-- here is the problem, the href is "#fn2:1"

2. Footnote text. ↩︎ ↩︎  <-- this list item id is "fn2"
```

Thanks for helping!

**Comment by rlidwka** [comment]
Fixed, thanks!
