### ISSUE TITLE
conflict with Link reference's  grammar

### ISSUE THREAD

**Issue by suziwen** [markdown-it/markdown-it-footnote#17]
markdown-it'sversion 8.3.0
markdown-it-footnote's version 3.0.1

```
Here is a footnote reference,[^1]

[^1]: Here
```

result

``` html
<p>Here is a footnote reference,<a href="Here">^1</a>
```

but I want this 

``` html
<p>Here is a footnote reference,<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup>
</p>
<hr class="footnotes-sep">
<div class="footnotes">
  <ol class="footnotes-list">
    <li id="fn1" class="footnote-item">
      <p>Here <a href="#fnref1" class="footnote-backref">↩︎</a>
      </p>
    </li>
  </ol>
```

**Comment by puzrin** [comment]
[Works as expected](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22Here%20is%20a%20footnote%20reference%2C%5B%5E1%5D%5Cn%5Cn%5B%5E1%5D%3A%20Here%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

If you still have problem with it - provide a minimal code sample how to reproduce.
