### ISSUE TITLE
Suggestion to change a look of duplicated references

### ISSUE THREAD

**Issue by johncja** [markdown-it/markdown-it-footnote#19]
Currently, duplicated references looks like this:

> Duplicated footnote reference<sup>[2:1]</sup>

Which means "first repeat of second footnote". From my very personal point of view, it looks a bit confusing. There are 2 reasons:

1. Reference "2:1" looks like subordinate of reference "2". (Like in numbered lists, where item "2.1" is always subordinate of item "2").
2. "2:1" is also looks like link to religious texts. For example, you could google "Numbers 14:18" to understand what I mean.

## Possible solution (Just a draft, I haven't seriously thinked about it. But at first glance, looks ok)

Use dash instead of colon. Also, if there are multiple references for single footnote, the first reference should be prefixed with 1-, second with 2- and so on. If there are only one reference, then there are no prefixes is needed. Example:

> Footnote 1 reference<sup>1</sup>
>
> Footnote 2 reference<sup>2-1</sup>
>
> Duplicated reference for second footnote<sup>2-2</sup>

## Update

Another idea, maybe even better, is just leave references plain. Example:

> Footnote 1 reference<sup>1</sup>
>
> Footnote 2 reference<sup>2</sup>
>
> Duplicated reference for second footnote<sup>2</sup>

This is more logical, because reference is link to "something". And so, references "2:1" and "2:2" could be incorrectly interpreted by the reader as links to different footnotes.

Wikipedia agrees with me, see screenshot. There are no pre- or post-fixes before/after "[3]" in main text.

![image](https://cloud.githubusercontent.com/assets/18004961/26157558/32a55e2e-3b22-11e7-8588-4975b8202295.png)

Screenshot taked from article about Times New Roman. You could check it yourself:
https://en.wikipedia.org/wiki/Times_New_Roman

**Comment by puzrin** [comment]
No plans to change defaults now. You can override renderer and customize look for your needs. That does not require any change in package.

**Comment by johncja** [comment]
Ok, thanks. As I understand, you mean some custom function, like shown in markdown-it-container readme, right?

``` js
md.use(require('markdown-it-container'), 'spoiler', {

  validate: function(params) {
    return params.trim().match(/^spoiler\s+(.*)$/);
  },

  render: function (tokens, idx) {
    var m = tokens[idx].info.trim().match(/^spoiler\s+(.*)$/);

    if (tokens[idx].nesting === 1) {
      // opening tag
      return '<details><summary>' + md.utils.escapeHtml(m[1]) + '</summary>\n';

    } else {
      // closing tag
      return '</details>\n';
    }
  }
});
```

Hm, probably will be a little big for newbies like me, hah :smiley:
