### ISSUE TITLE
Directly loading into browser complains Uncaught SyntaxError

### ISSUE THREAD

**Issue by tamlok** [markdown-it/markdown-it-footnote#20]
Hi, I try to use this plugin directly from plugin. I download it from the `dist/` folder.

```
mdit = mdit.use(window.markdownitFootnote);
```

It will complain:

```
Critical:(markdown-it-footnote.min.js:7) Uncaught SyntaxError: Unexpected token <
Critical:(markdown-it-footnote.min.js:2) Uncaught TypeError: Cannot read property 'apply' of undefined
```

Thanks very much!

**Comment by puzrin** [comment]
No ideas. Try not minified version, if problem still exists - prepare standalone repo with minimal sample.

**Comment by tamlok** [comment]
Thanks! The problem still exists in non-minified version. I will try to prepare a minimal sample to reproduce it. :)

**Comment by johncja** [comment]
@tamlok Works for me:

``` js
var mdConverter = window.markdownit({
    html:         true,
    breaks:       true,
    linkify:      true,
    typographer:  false
    })
        .use(window.markdownitMark)
        .use(window.markdownitFootnote);
```

**Comment by tamlok** [comment]
@johncja Thanks very much! Finally got it work. I found that I had downloaded the wrong file from Github by directly "save link as" on the file names, instead of going to the **raw** page. ~~ Thanks very much!
