### ISSUE TITLE
Footnotes are not replaced when markdown is reparsed

### ISSUE THREAD

**Issue by Syndesi** [markdown-it/markdown-it-footnote#22]
Hi,

I find your plugin very usefull and good programed, but every time I call `md.render(text);` again (e.g. when I changed the markdown from the editor), the existing footnotes aren't removed and the parsed ones are just appended :/

I *think* it could have something to do with the `state`-variable of the plugin, but I'm not sure. But at least I can say that the document-DOM don't cause the problem because I save the generated DOM inside a variable and render it with React, so everything is replaced on every change.

And here are some images:

![md.render only called once](https://user-images.githubusercontent.com/9903723/33782850-97e39056-dc5a-11e7-8811-b76cfc9735ad.png)
![md.render called another time](https://user-images.githubusercontent.com/9903723/33782851-9806daf2-dc5a-11e7-940f-78c0f39ef234.png)
![md.render called a third time](https://user-images.githubusercontent.com/9903723/33782852-982738e2-dc5a-11e7-9862-a9454a57db54.png)
![md.render called multiple times to show how "ugly" multiple footnotes can be](https://user-images.githubusercontent.com/9903723/33782853-98471388-dc5a-11e7-8ed6-3d9434e8f48f.png)

I hope this is fixable :)

**Comment by Syndesi** [comment]
Btw., if I remove the footnote completely, the list disapears. But if I add again a footnote, all notes from the whole "session" come back - maybe they are stored internally?

**Comment by puzrin** [comment]
There are no global state here, it's created [every time](https://github.com/markdown-it/markdown-it/blob/3353462142d519dfe5b613e4d9e79fa29601ff98/lib/index.js#L541) if you do not forse pass shared obj.

I'm sure everything works as needed. But you may try to create test repo with minimal code sample, and i will take a look.

**Comment by Syndesi** [comment]
Ok thank you, I'll definetly do this! :D

**Comment by Syndesi** [comment]
Ok, the [demo is finished](https://github.com/markdown-it/markdown-it-footnote/files/1543918/demo.zip). It's still based on React, but I added many comments and the following readme:

---

Code sample for the [issue 22](https://github.com/markdown-it/markdown-it-footnote/issues/22) of markdown-it-footnote

## How to run the code (live)

1. Download an install [Yarn](https://yarnpkg.com/lang/en/).
2. Open a terminal in this folder.
3. Run `yarn install`, it will install all dependencys of this demo.
4. Run `yarn start` to start the local webserver.
5. Open [http://localhost:8080](http://localhost:8080) in your browser.
6. Play with the textarea on the right, every Markdown will be compiled into HTML instantly.

## How to run the code (precompiled)

1. Go into the folder `./dist/`.
2. Open `index.html` with your browser.
3. Note: This way you can not change the code anymore and the fonts are not loaded (unless the fonts are in the root folder).

---

[Download the demo here](https://github.com/markdown-it/markdown-it-footnote/files/1543918/demo.zip)

**Comment by puzrin** [comment]
Sorry, no time to learn all this. Just create a minimal possible example to run from node.js. And in separate repo, to make `git clone .....`, `npm install`, `node index.js`

**Comment by Syndesi** [comment]
I'll try, but the last time I used npm was early 2016 ^^

**Comment by puzrin** [comment]
Minimal possible example is something like [this](https://github.com/markdown-it/markdown-it-footnote#use) in index.js + packge.json

**Comment by Syndesi** [comment]
Hi,

I replaced Yarn by NPM and reduced the code even more. Now all the important things are in one single file with only 48 lines. And the "biggest" change: It's now online in its own repository: [https://github.com/Syndesi/markdown-it-footnote-issue-demo](https://github.com/Syndesi/markdown-it-footnote-issue-demo).

The code is still based on React, but I only used it to listen for changes in the textarea and rerendering the generated markdown-dom.

**Comment by puzrin** [comment]
Sorry, can't help with this. If you need my help, please provide minimal sample as i explained - executable from cli, no react etc. Only small executable js with example, what is wrong with this package.

**Comment by Syndesi** [comment]
Can you please at least run the .html-file in the dist-folder while I'm replacing React with basic JS?

**Comment by puzrin** [comment]
I see that bug, but IMHO it's somewhere at your side. I'm not sure you will be able to reproduce it in smallest possible minimal sample

**Comment by Syndesi** [comment]
Yep, as you suspected it works fine if I don't use React (therefore plain JS) and I now *could* think why: In react every element needs a key so it is unique and traceable. When that's not the case, bugy things like these can arise.
But normally I get a warning but this time it wasn't the case.

Never the less I want to thank you for your time and fast response :)

**Comment by Syndesi** [comment]
Ok, bug fixed. It wasn't actually the "key-bug" but some weird *React caches Markdown-it stuff* and now I'm creating the Markdown-it-object on every update.
