### ISSUE TITLE
How to create a footnote link that open in a new window/tab?

### ISSUE THREAD

**Issue by joetidee** [markdown-it/markdown-it-footnote#23]
I currently have a footnote like this:

Click [here][go-to-site] to visit Google.
...
[go-to-site]: https://www.google.com

How can I make this link open in a new tab/window?

**Comment by puzrin** [comment]
I guess, you need to override default renderer https://github.com/markdown-it/markdown-it-footnote/blob/4f0f468ac2a64c00c3b709b0d49f57d607c93c2e/index.js#L29
