### ISSUE TITLE
readability of multiple references

### ISSUE THREAD

**Issue by RuBru** [markdown-it/markdown-it-footnote#26]
Multiple reference footnotes are cool, but currently confusing for human eye .
`This is an example with single reference[1], but these are multi-references - one[2], two[2:1] and three[2:2].`

my suggestion for multiple reference:
* start counting from 1
* if there are multiple references, show second part in all of them

`This is an example with single reference[1], but these are multi-references - one[2:1], two[2:2] and three[2:3].`

**Comment by puzrin** [comment]
That's subjective and out of project scope. You can override default templates as you wish.
