### ISSUE TITLE
Error thrown on a specific footnote

### ISSUE THREAD

**Issue by deanebarker** [markdown-it/markdown-it-footnote#27]
I was getting an error, and kept removing stuff until I isolated the error down to a single footnote.

```
The document we're working towards is often called a "Project Charter." The Project Management Institute [^pmi] defines the charter as:

[^pmi]: [Project Management Institute](https://www.pmi.org/)
```

That results in this error:

```
TypeError: Cannot read property 'type' of undefined
    at Array.footnote_tail (C:\Users\Deane\Dropbox\Sync\Desktop\js\splitting\node_modules\markdown-it-footnote\index.js:335:49)
    at Core.process (C:\Users\Deane\Dropbox\Sync\Desktop\js\splitting\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (C:\Users\Deane\Dropbox\Sync\Desktop\js\splitting\node_modules\markdown-it\lib\index.js:523:13)
    at MarkdownIt.render (C:\Users\Deane\Dropbox\Sync\Desktop\js\splitting\node_modules\markdown-it\lib\index.js:543:36)
```

There were other footnotes in the original chunk of Markdown -- no error. But this one footnote caused the error -- I kept removing stuff and putting it back until I identified this one.

Here's the offending line from the code:

```
if (state.tokens[state.tokens.length - 1].type === 'paragraph_close') {
```

https://github.com/markdown-it/markdown-it-footnote/blob/master/index.js#L335

Why would this particular footnote throw an error?

**Comment by puzrin** [comment]
[it works](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22The%20document%20we%27re%20working%20towards%20is%20often%20called%20a%20%5C%22Project%20Charter.%5C%22%20The%20Project%20Management%20Institute%20%5B%5Epmi%5D%20defines%20the%20charter%20as%3A%5Cn%5Cn%5B%5Epmi%5D%3A%20%5BProject%20Management%20Institute%5D%28https%3A%2F%2Fwww.pmi.org%2F%29%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Can not reproduce. Could you create a test repo with minimal code sample?

**Comment by deanebarker** [comment]
I see now what makes it happen, but not why. Turns out, it has nothing to do with that footnote.

It happens when you assign the `markdown-it` module to a local variable _and reuse it_.

```
const md = require('markdown-it')('commonmark')

let text = [
`foo [^foo]
[^foo]: Foo`,
`bar [^bar]
[^bar]: Bar`
]

text.forEach(el => {
    console.log(require('markdown-it')('commonmark').use(require('markdown-it-footnote')).render(el))
})
```

That will cause the error on the _second iteration_ (if you catch error, you can add more elements and it actually errors on _every iteration after the first_).

If the array only has one element, it does not occur. 

Additionally, if you import the module "fresh" each time, like this...

```
console.log(md.use(require('markdown-it-footnote')).render(el))
```

...it doesn't occur either.

So, it has something to do with re-use of the module, which means I have fixed it in my code, but it still seems like something that shouldn't throw an error.

**Comment by puzrin** [comment]
You should NOT call `.use()` in cycle. Readme contains correct example https://github.com/markdown-it/markdown-it-footnote#use.

This should work:

```js
const md = require('markdown-it')('commonmark')
  .use(require('markdown-it-footnote');

let text = [
`foo [^foo]
[^foo]: Foo`,
`bar [^bar]
[^bar]: Bar`
];

text.forEach(el => {
  console.log(md.render(el));
})
```

**Comment by deanebarker** [comment]
>You should NOT call .use() in cycle

Is that for all plugins, or just this one?

**Comment by puzrin** [comment]
All.
