### ISSUE TITLE
Syntax for inline footnotes

### ISSUE THREAD

**Issue by ejfox** [markdown-it/markdown-it-footnote#32]
Right now the syntax for inline footnotes in markdown-it-footnote as follows:

```
Here is an inline note.^[Inlines notes are easier to write, since
you don't have to pick an identifier and move down to type the
note.]
```

However referencing some other resources markdown parsers, we find that there are a variety of implementations. I first discovered this because I was creating my posts in the markdown editor IA Writer and the footnotes rendered properly in the preview, but not when rendered through markdown-it. 

Here are some other implementations I've dug up:

[IA writer](https://ia.net/writer/support/general/markdown-guide)
`Some text with a footnote[^This is the footnote itself.].`

[MultiMarkdown](https://fletcher.github.io/MultiMarkdown-5/footnotes.html)
`Here is another footnote.[^This is the footnote itself]`

[Pandoc](https://pandoc.org/MANUAL.html)
`Here is an inline note.^[Inlines notes are easier to write, since
you don't have to pick an identifier and move down to type the
note.]`

[rephrase.net](https://rephrase.net/box/word/footnotes/syntax/) PHP-Markdown
`I met Jim [^](My old college roommate) at the station.`

---

Would it be worth it to support all of these implementations? If so, where might someone get started on implementing that? 

Thank you!

**Comment by puzrin** [comment]
Since there are no unified spec, and commonmark still not defined this extension, there are no plans to change this package. Anyone, interested in oner syntax, can implement it's own plugin. markdown-it allow change almost everything and make you independent on author's opinion.
