### ISSUE TITLE
URL in inline footnotes are not recognized

### ISSUE THREAD

**Issue by desk7** [markdown-it/markdown-it-footnote#33]
If you type an URL in a inline footnote, it is not rendered as link but as plain text.

```text
Example^[this is another example https://github.com]
```
Given that Markdown parses links and converts them into clickable links, even in `longnote`, it should work in inline footnotes too.

**Comment by rlidwka** [comment]
Fixed, thanks!

**Comment by tessus** [comment]
@rlidwka can you please create a new release `3.0.2`, otherwise it will be hard to get this fix in other projects.
