### ISSUE TITLE
Should footnote definitions starting on a separate line be supported?

### ISSUE THREAD

**Issue by jozefs** [markdown-it/markdown-it-footnote#36]
[Prettier](https://github.com/prettier/prettier)'s formatting rules do not play nicely with markdown-it-footnote.

It transforms this:
```
[^1]: This is a footnote that is longer than the maximum line length, or even an entire paragraph.
```

Into this:

```
[^1]:
  This is a footnote that is longer than the maximum line
  length, or even an entire paragraph.
```

markdown-it-footnote does not recognize the above as a valid footnote. I was wondering if this was a deliberate decision to not support that format, a bug or a missing feature?

**Comment by puzrin** [comment]
That's a delibirate dicusion. We just copied pandoc's principle until CommonMarc spec inclues "right" definition.
