### ISSUE TITLE
why that happen when write a code and validate ? Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

### ISSUE THREAD

**Issue by uzairlucki** [markdown-it/markdown-it-footnote#37]
![image](https://user-images.githubusercontent.com/32535552/86772348-403e1480-c06d-11ea-8392-9439cc0c0e15.png)

**Comment by puzrin** [comment]
No ideas. Please provide minimal sample with details how to reproduce & explain why this issue related to this repo. Also note, you can modify rendering templates as you wish.

**Comment by uzairlucki** [comment]
actually i convert PSD into html bootstrap, when i debug on tester then above issue find out.

**Comment by puzrin** [comment]
I can help only with issues about this package, not with general things. If you add more info why this issue is package-specific, and how to reproduce, we can continue.
