### ISSUE TITLE
Placing footnote at bottom of Slide not at the end of the Presentation 

### ISSUE THREAD

**Issue by StefanZander** [markdown-it/markdown-it-footnote#38]
Preamble: 
This is more of a question than an issue and it might be more related to the marp project.
In any case thank you in advance for considering it.

Motivation:
I want to shift all my lecture slides to markdown and use the marp framework for generating the html/pdf output. One feature that I really like is the use of footnotes -- therefore I really appreciate the existence of your extension.

Issue:
When using footnotes, the actual footnotes are placed at the end of the document, ie., on the last slide rather than the slide on which the footnote declaration was placed.

Question:
Atm, I don't know wether this is a marp- or extension-related issue and I hope you could shed some light into it.

Thank you very much in advance and best regards.

**Comment by puzrin** [comment]
Markdown does not know anything about "multiple pages". It operates in context of single page:

```
source page (md) => parser => output page (html)
```

Everything else is organised via outer tools on upper abstracion layer. So, in this case answer is "this is marp issue". It should care about proper source split and render each peace (page) independent. Then foonotes will be "local" for every page.

**Comment by StefanZander** [comment]
Thanks @puzrin for the answer and the background information.

I will create a new issue in the marp-cli project and ask for help there.
