### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by jtppragg** [markdown-it/markdown-it-footnote#39]
I am trying to use markdown-it-footnote from marp-cli but I always get the following error message:

> Cannot read property 'type' of undefined

Here there is my `engine.js` code:

```javascript
const { Marp } = require('@marp-team/marp-core')

module.exports = (opts) => new Marp(opts)
        .use(require('markdown-it-container'), 'columns')
        .use(require('markdown-it-footnote'))
        .use(require('markdown-it-mark'))
```
I use several markdown-it plugins, but the error only appears when enabling markdown-it-footnote.

Thanks!

**Comment by puzrin** [comment]
I think you should address your question to marp authors. Markdown-it has online demo with this plugin, working as expected.
