### ISSUE TITLE
Normal Footnotes - Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by mashdot** [markdown-it/markdown-it-footnote#41]
Recently I am unable to use Normal Footnotes with references.

```
Something[^1] something else

[^1]: blah blah 
```

This causes as `Cannot read property 'type' of undefined` error which then points to:

`node_modules/markdown-it-footnote/index.js:338:49`

Which is:

```
state.tokens = state.tokens.concat(tokens);
      if (state.tokens[state.tokens.length - 1].type === 'paragraph_close') {
        lastParagraph = state.tokens.pop();
      } else {
        lastParagraph = null;
      }
```

However, your Inline Footnotes do still work fine and cause no errors.
      
```
Something^[blah blah] something else
```

Any ideas?

**Comment by rlidwka** [comment]
I'm unable to reproduce this error. Just tried this code snippet and it works fine:

```js
var md = require('markdown-it')()
            .use(require('markdown-it-footnote'));

console.log(md.render(`
Something[^1] something else

[^1]: blah blah
`.trim()));
```

Please show a minimal example of the code that produces this error.

**Comment by mashdot** [comment]
Just for future seekers, it appears to be related to Nunjucks template processing in 11ty. 

I don't have an answer why yet, but at least I know it is not caused by markdown-it-footnote directly.

**Comment by puzrin** [comment]
That's usually caused by missed second param of `.parse()` call.

**Comment by mashdot** [comment]
Oh? How would I resolve this?

**Comment by mashdot** [comment]
Discovered more about the issue. I used to use .md files as my layouts, which included nunjucks and this was parsed with 11ty. For some reason this has stopped working. So changed the extension to .njk which forces nunjucks parsing first and I no longer get the above issue.
