### ISSUE TITLE
erroneous markdown leads to crash

### ISSUE THREAD

**Issue by ckruse** [markdown-it/markdown-it-footnote#42]
Hi,

given this source code:

~~~
foo[^1] bar[^2].

[^1]:[^2]: baz
~~~

markdown-it-footnote fails with this error and stacktrace:

~~~
Uncaught TypeError: state.tokens[(state.tokens.length - 1)] is undefined
    footnote_tail index.js:338
    process parser_core.js:51
    parse index.js:524
~~~

While I understand that this is no valid markdown I don't think the parser should fail. Is this a bug?

Best regards,
 CK

**Comment by puzrin** [comment]
That's a bug. Markdown source can not be "invalid".

**Comment by rlidwka** [comment]
fixed, thanks for reporting

**Comment by ckruse** [comment]
Thank you very much for your work!
