### ISSUE TITLE
how to use without require

### ISSUE THREAD

**Issue by OrenBochman** [markdown-it/markdown-it-footnote#45]
Thanks for adding footnote support.

For devs who are not coding for node please also document  how to import this module for use a js module with imports  instead of using require.

**Comment by Nekkowe** [comment]
I came across this issue while looking for the right syntax to do this with eleventy, and found the solution a bit later:
```js 
import markdownItFootnote from "markdown-it-footnote";
// etc...
export default async function(eleventyConfig) {
  // etc... 
  eleventyConfig.amendLibrary("md", (mdLib) => mdLib.use(markdownItFootnote));
  // etc...
}
```
