### ISSUE TITLE
markdown-it-footnote and vuepress 2.0.0-rc.0 are not compatible

### ISSUE THREAD

**Issue by aoleou** [markdown-it/markdown-it-footnote#51]
Hi, Excuse me, have you considered making markdown-it-footnote compatible with vuepress 2.0.0-rc.0? When I upgrade to vuepress 2.0.0-rc.0, the error is gona come to say **not support dynamic require**. May be ESM of markdown-it-footnote will compatible with vuepress 2.0.0-rc.0

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-footnote/blob/master/rollup.config.mjs#L57 there are different builds in `dist/` folder, including full ones. Try one if direct ESM import does not work for some reason.
