### ISSUE TITLE
W3C: "Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections."

### ISSUE THREAD

**Issue by ToniWonKanobi** [markdown-it/markdown-it-footnote#6]
Have you considered adding a heading to the footnotes `<section>`? I ask because when checking my site for errors on the W3C's validator, I consistently get errors relating to the lack of a section heading for the footnotes section:

![Section lacks heading](http://d.pr/i/1fHo5+ "Section lacks heading")

Perhaps something like so

```
<section class="footnotes">
<h3 class="footnotesheading">Footnotes</h3>
<ol class="footnotes-list">
```

This is mostly a question of semantics.

Note that the actual heading could be set to `display: none` via CSS, so that it doesn't show in the stylized version of the webpage.

**Comment by puzrin** [comment]
That's a question of specification. I try to stay aside if such things to not promote new standards. It would be better to discuss such things at http://talk.commonmark.org/ .

As soon as spec will be ready, i will update layout. If you can't wait - overwrite renderer fns as usual.

**Comment by ToniWonKanobi** [comment]
Okay :)

PS: How could I overwrite renderer functions if `markdown-it-footnote` is a dependency of my web app? (I don't think I can make changes to an `npm` package that is a dependency).

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer

The same way as footnote modify behavior of main parser.

**Comment by ToniWonKanobi** [comment]
Got it. Thanks!

**Comment by ToniWonKanobi** [comment]
Ahh. I had never seen that page before. (I usually just check the npmjs registry, but maybe I should look here more often.)




On December 2, 2015 at 5:17:30 PM, Vitaly Puzrin (notifications@github.com) wrote:

https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer

The same way as footnote modify behavior of main parser.
